In [16]:
import pandas as pd
data = pd.read_csv('bottle_1.1THz.csv', index_col=0)

In [17]:
data.head()

                          Sharpness  Contrast  BRISQUE
resol1951_2_e_0.1_to_0.1      17.18     66.91    30.13
resol1951_2_e_0.1_to_0.2       6.78     34.36     7.91
resol1951_2_e_0.1_to_0.3       6.77     34.04     4.89
resol1951_2_e_0.1_to_0.4       7.16     35.76    14.28
resol1951_2_e_0.1_to_0.5       7.29     32.87    15.00

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 900 entries, resol1951_2_e_0.1_to_0.1 to resol1951_2_e_3.0_to_3.0
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sharpness  900 non-null    float64
 1   Contrast   900 non-null    float64
 2   BRISQUE    900 non-null    float64
dtypes: float64(3)
memory usage: 28.1+ KB

In [19]:
data.describe()

        Sharpness    Contrast     BRISQUE
count  900.000000  900.000000  900.000000
mean    15.748756   60.038078   30.972422
std      7.790463   18.303673   15.795435
min      3.960000    8.560000  -11.230000
25%      9.375000   49.875000   22.367500
50%     15.190000   62.635000   30.555000
75%     19.715000   72.582500   39.047500
max     34.180000   92.980000   95.490000

In [66]:
# data = data[(data > 12).all(1)]

In [67]:
def get_max(metric='Sharpness'):
    print(f'MAX {metric}: ', end='')
    print(data.index[data[metric].argmax()], data[metric].max())

def get_min(metric='BRISQUE'):
    print(f'MIN {metric}: ', end='')
    print(data.index[data[metric].argmin()], data[metric].min())

In [68]:
get_max('Sharpness')
get_max('Contrast')
get_min('BRISQUE')

MAX Sharpness: resol1951_2_e_0.8_to_2.4 34.18
MAX Contrast: resol1951_2_e_0.6_to_2.3 92.98
MIN BRISQUE: resol1951_2_e_1.0_to_2.5 21.26